spring:
  kafka:
    bootstrap-servers: localhost:9092


grpc:
  server:
    port: 59091

server:
  port: 8080

logging:
  level:
    ru.yandex.practicum.collector: DEBUG
    org.springframework.grpc: DEBUG
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"