spring:
  application:
    name: aggregator
  config:
    import: "configserver:"  # УБРАТЬ явный URL
  cloud:
    config:
      discovery:
        enabled: true        # ВКЛЮЧИТЬ обнаружение через Eureka
        serviceId: config-server  # Имя сервиса Config Server в Eureka

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/

server:
  port: 8081