spring:
  application:
    name: shopping-store
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        userRandomPolicy: true
        max-interval: 6000
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  instance:
    # 1. Принудительное использование localhost для регистрации в Eureka
    hostname: localhost
    # 2. Использование IP-адреса, если hostname не помог (дополнительная мера)
    prefer-ip-address: true

server:
  port: 36135
